on: [push]

defaults:
  run:
    shell: sh

env:
  PANDOC_VERSION: 2.19

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1.0.0
        with:
          version: ${{ env.PANDOC_VERSION }}

      - name: Test theorems
        run: make test
        working-directory: theorems
