on: [push]

defaults:
  run:
    shell: sh

jobs:
  ci:
    name: ${{ matrix.os }} / Pandoc ${{ matrix.pandoc-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        pandoc-version: ["2.19.2", "3.0.1"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Setup Pandoc ${{ matrix.pandoc-version }}
        uses: pandoc/actions/setup@v1.0.0
        with:
          version: ${{ matrix.pandoc-version }}

      - name: Test theorems
        run: make test
        working-directory: theorems
