on: [push]

defaults:
  run:
    shell: sh

jobs:
  ci:
    name: ${{ matrix.os }} / Pandoc ${{ matrix.pandoc-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        pandoc-version:
          - "2.17"
          - "2.17.0.1"
          - "2.17.1"
          - "2.17.1.1"
          - "2.18"
          - "2.19"
          - "2.19.1"
          - "2.19.2"
          - "3.0.1"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Pandoc ${{ matrix.pandoc-version }}
        uses: pandoc/actions/setup@v1.0.0
        with:
          version: ${{ matrix.pandoc-version }}

      - name: Test embed_pdf filter
        run: make test
        working-directory: embed_pdf

      - name: Test possessive_cite filter
        run: make test
        working-directory: possessive_cite

      - name: Test theorem filter
        run: make test
        working-directory: theorem
